#!/usr/bin/env bash

docker build --no-cache -f docker/Dockerfile -t tricore-builder . || { echo "Error while building mingw toolchain"; exit 1; }
echo "Exporting compiler distributables..."
mkdir -p out
docker run --rm -v $(pwd)/out:/output tricore-builder
