name: Build

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu 22.04
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc g++ texinfo make flex bison libmpfr-dev libgmp-dev libmpc-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: ./build-toolchain
